# .github/workflows/update_stats.yml

name: Metrics
on:
  # Run automatically every 6 hours
  schedule:
    - cron: '0 */1 * * *'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  # Also run on every push to the main branch
jobs:
  metrics:
    runs-on:
    steps:
      - name: Main Content
        if: ${{ success() || failure() }}
        uses: lowlighter/metrics@latest
        with:
          filename: github-metrics.svg
          token: ${{ secrets.GH_TOKEN }}
          
          base: header, activity, community, repositories, metadata
          
        
          plugin_isocalendar: yes
          plugin_languages: yes
          plugin_lines: yes
          
          # Languages options
          plugin_languages_limit: 8
          plugin_languages_threshold: 0%
          
          # Lines of code options
          plugin_lines_history: yes
          plugin_lines_sections: header, footer
          plugin_lines_indepth: yes
      - name: Achievements
        if: ${{ success() || failure() }}
        uses: lowlighter/metrics@latest
        with:
          filename: achievements.svg
          token: ${{ secrets.GH_TOKEN }}

          base: ""
          output_action: gist
          committer_gist: ${{ secrets.GIST }}
          plugin_achievements: yes
          plugin_achievements_display: compact
          plugin_fortune: yes
 
