# .github/workflows/update_stats.yml

name: Metrics
on:
  # Run automatically every 6 hours
  schedule:
    - cron: '0 */6 * * *'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  # Also run on every push to the main branch
  push:
    branches:
      - main
      - master

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Needed to write the generated files
    steps:
      - uses: lowlighter/metrics@latest
        with:
          # Your GitHub token
          token: ${{ secrets.GH_TOKEN }}

         
          base: header, activity, community, achievements, repositories, metadata
          
          # --- ENABLED PLUGINS ---
          plugin_isocalendar: yes
          plugin_languages: yes
          plugin_lines: yes
          plugin_achievements: yes # Enable the achievements plugin

          # --- LANGUAGES PLUGIN OPTIONS ---
          plugin_languages_limit: 8
          plugin_languages_threshold: 0%
          
          plugin_lines_sections: header, footer
          
          # --- ACHIEVEMENTS PLUGIN OPTIONS ---
          plugin_achievements_display: compact
          plugin_achievements_threshold: C
          plugin_achievements_limit: 6
          
 
