# .github/workflows/update_stats.yml

name: Metrics
on:
  # Run automatically every 6 hours
  schedule:
    - cron: '0 */1 * * *'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  # Also run on every push to the main branch
  push:
    branches:
      - main
      

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Needed to write the generated files
    steps:
      - uses: lowlighter/metrics@latest
        with:
          # Your GitHub token
          # This will use the GH_TOKEN secret you already created
          token: ${{ secrets.GH_TOKEN }}

         
          # The base content of the file
          base: header, activity, community, repositories, metadata
          
        
          plugin_isocalendar: yes
          plugin_languages: yes
          plugin_lines: yes
          
          # Languages options
          plugin_languages_limit: 8
          plugin_languages_threshold: 0%
          
          # Lines of code options
          plugin_lines_history: yes
          plugin_lines_sections: header, footer
          plugin_lines_indepth: yes

          # Timezone
