# .github/workflows/update_stats.yml

name: GitHub Stats Card

on:
  # Run automatically every 6 hours
  schedule:
    - cron: '0 */6 * * *'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Update GitHub Stats Card
        uses: anuraghazra/github-readme-stats@master
        with:
          # This is the PAT you stored as a secret
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          # The username of the account
          USERNAME: ${{ github.repository_owner }}
          # The file to write the stats to
          TO_FILE: 'generated/stats.svg'
          # Other options
          SHOW_ICONS: 'true'
          THEME: 'tokyonight' # Change this to your preferred theme
          COUNT_PRIVATE: 'true'
          HIDE_BORDER: 'true'

      - name: Update Top Languages Card
        uses: anuraghazra/github-readme-stats@master
        with:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          USERNAME: ${{ github.repository_owner }}
          TO_FILE: 'generated/langs.svg'
          LAYOUT: 'compact'
          THEME: 'tokyonight' # Change this to your preferred theme
          COUNT_PRIVATE: 'true'
          HIDE_BORDER: 'true'

      - name: Commit and Push
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add .
          # The [skip ci] part is important to prevent an infinite loop of actions
          git commit -m "chore: update stats [skip ci]" || exit 0
          git push
