# .github/workflows/update_stats.yml

name: Metrics
on:
  # Run automatically every 6 hours
  schedule:
    - cron: '0 */6 * * *'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  # Also run on every push to the main branch
  push:
    branches:
      - main
      - master

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Needed to write the generated files
    steps:
      - uses: lowlighter/metrics@latest
        with:
          # Your GitHub token
          # This will use the GH_TOKEN secret you already created
          token: ${{ secrets.GH_TOKEN }}

          # OPTIONS
          # The base content of the file
          base: header, activity, community, repositories, topics, languages, metadata

          # ------------------------------------------------------------------
          # TOPICS PLUGIN CONFIGURATION (WORD CLOUD)
          # ------------------------------------------------------------------
          plugin_topics: yes
          plugin_topics_limit: 15               # Display the 15 most used topics
          plugin_topics_sort: stars             # Sort by most-starred repos
          plugin_topics_mode: icons             # Display topics as icons with text
          plugin_topics_title: Most Used Topics # Optional: Custom title
          # ------------------------------------------------------------------

          # Other plugins you have enabled
          plugin_languages: yes
          plugin_languages_limit: 8
          plugin_isocalendar: yes
          plugin_lines: yes
          
          # Languages options
          plugin_languages_threshold: 0%
          
          # Lines of code options
          plugin_lines_history: yes
          plugin_lines_sections: header, footer
          plugin_lines_indepth: yes

          # You can change the timezone
          config_timezone: America/New_York
