# .github/workflows/update_stats.yml

name: Metrics
on:
  # Run automatically every 6 hours
  schedule:
    - cron: '0 */6 * * *'
    
  workflow_dispatch:

  push:
    branches:
      - main
      - master

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write 
    steps:

      - uses: lowlighter/metrics@latest
        with:
          # Your GitHub token
          token: ${{ secrets.GH_TOKEN }}

          # Add "topics" to the base layout
          base: header, activity, community, repositories, topics, languages, metadata

          # ------------------------------------------------------------------
          # TOPICS PLUGIN CONFIGURATION (WORD CLOUD)
          # ------------------------------------------------------------------
          plugin_topics: yes
          plugin_topics_limit: 15               # Display the 15 most used topics
          plugin_topics_sort: stars             # Sort by most-starred repos
          plugin_topics_mode: icons             # Display topics as icons with text
          plugin_topics_title: Most Used Topics # Optional: Custom title
          # ------------------------------------------------------------------

          # Other plugins you have enabled
          plugin_languages: yes
          plugin_languages_limit: 8

          plugin_achievements: yes
          plugin_achievements_only: sponsor, maintainer, octonaut
          
          # ... any other plugins like lines, isocalendar, etc.
